### ISSUE TITLE
Give credits

### ISSUE THREAD

**Issue by tvlad1234** [ElectroBoy404NotFound/LinuxAVR#1]
Hi. I've noticed your repository is a reupload of Dmitry Grinberg's code from [here](http://dmitry.gr/?r=05.Projects&proj=07.%20Linux%20on%208bit). You need to at least give credit.

**Comment by ElectroBoy404NotFound** [comment]
Hi @tvlad1234 ,
Thank you for the reminder!
I made this repository only for the codespace to compile and get the files as i didnt have a linux machine nor a vm.
Anyways, i will add the credits.
Regards,
ElectroBoy404NotFound

**Comment by ElectroBoy404NotFound** [comment]
Done
